apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: rp
  name: rp
spec:
  replicas: 2
  selector:
    matchLabels:
        app: rp
  template:
    metadata:
      labels:
        app: rp
        service: rp
    spec:
      containers:
      - image: dominikjaeckle3000/uc-refactor-reverseproxy:latest
        name: rp
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
      restartPolicy: Always
