version: "3"
services:
  reverseproxy:
    build:
      context: ../reverseproxy
    image: dominikjaeckle3000/uc-refactor-reverseproxy:latest
  backend_user:
    build:
      context: ../backend-user
    image: dominikjaeckle3000/uc-refactor-backend-user:latest
  backend_feed:
    build:
      context: ../backend-feed
    image: dominikjaeckle3000/uc-refactor-backend-feed:latest
  frontend:
    build:
      context: ../frontend
    image: dominikjaeckle3000/uc-refactor-frontend:latest
